In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

## Caso AND y OR

#### Generación de $S_n=\lbrace(x^{(i)},y^{(i)}),i=1,\ldots,n\rbrace$

In [2]:
#Caso OR
n = 200
rs = np.random.RandomState(seed=1751)
x1 = ( rs.uniform(size=n) >=0.5 ).astype(int)
x2 = ( rs.uniform(size=n)>=0.5 ).astype(int)

In [3]:
Sn = pd.DataFrame({'x1':x1,'x2':x2})
Sn['y'] = np.logical_and(Sn['x1'], Sn['x2']).astype(int)
Sn.head()
X = Sn[['x1','x2']]
X = X.values
y = Sn['y'] # Es una serie
y = y.values
Xt, Xv, yt, yv = train_test_split(X,y,train_size=0.7) # El 70 % de los datos ira a entrenamientoo

array([[1, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [0, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [1,

#### Perceptrón

In [8]:
'''T = 10000
theta = np.array([0,0])
for t in range(T):
    for i  in range(n):
        if Sn[i][-1]*(np.dot(theta,Sn[i][:2]))<=0:
            theta += Sn[i][-1]*Sn[i][:2] '''
T = 10
k=yt.size
theta = np.array([0,0])
for t in range(T):
    for i  in range(k):
        if yt[i] * ( np.dot(theta, Xt[i] ) )<=0:
            theta += yt[i]*Xt[i]
            print("y==",yt[i])
            print("dot product==",np.dot(theta, Xt[i] ) )

y== 1
dot product== 2
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot 

y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot 

y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 1
y== 0
dot product== 0
y== 0
dot product== 0
y== 0
dot 

##### $\theta = [\theta_1,\theta_2]^T$  ;  $\hat{\theta} = [1,1]^T$

In [152]:
theta

array([1, 1])

##### Verificación de que tan bueno es el modelo

In [153]:
def accuracy_artesanal(X,y,theta):
    O=0
    tam=y.size
    for i in range(tam):
        O += ( np.dot(theta, X[i] ) == y[i] ).astype(int)
    return O/tam

In [154]:
print(accuracy_artesanal(Xt,yt,theta))
print(accuracy_artesanal(Xv,yv,theta))

0.7357142857142858
0.8166666666666667


### Perceptron medio

In [174]:
def perceptron_medio(y,X):
    T = 2
    n=y.size
    theta = np.array([0,0])
    thetag = np.array([0,0])
    c = 1
    for t in range(1,T):
        for i  in range(1,n):
            if y[i] * ( np.dot(theta, X[i] ) )<=0:
                theta += y[i]*X[i]
                thetag =  thetag + (y[i]*X[i])*c
            c = c - (1/( n*T ) )
            print("Theta=",theta)
            print("Theta gorro=",thetag)
    print(c)
    return thetag

In [102]:
prueba = np.array([1,4])
4.4*(yt[1]*Xt[1])

array([0., 0.])

In [177]:
theta2=perceptron_medio(yt,Xt)
theta2

Theta= [0 0]
Theta gorro= [0 0]
Theta= [0 0]
Theta gorro= [0. 0.]
Theta= [0 0]
Theta gorro= [0. 0.]
Theta= [0 0]
Theta gorro= [0. 0.]
Theta= [0 0]
Theta gorro= [0. 0.]
Theta= [0 0]
Theta gorro= [0. 0.]
Theta= [0 0]
Theta gorro= [0. 0.]
Theta= [0 0]
Theta gorro= [0. 0.]
Theta= [1 1]
Theta gorro= [0.97142857 0.97142857]
Theta= [1 1]
Theta gorro= [0.97142857 0.97142857]
Theta= [1 1]
Theta gorro= [0.97142857 0.97142857]
Theta= [1 1]
Theta gorro= [0.97142857 0.97142857]
Theta= [1 1]
Theta gorro= [0.97142857 0.97142857]
Theta= [1 1]
Theta gorro= [0.97142857 0.97142857]
Theta= [1 1]
Theta gorro= [0.97142857 0.97142857]
Theta= [1 1]
Theta gorro= [0.97142857 0.97142857]
Theta= [1 1]
Theta gorro= [0.97142857 0.97142857]
Theta= [1 1]
Theta gorro= [0.97142857 0.97142857]
Theta= [1 1]
Theta gorro= [0.97142857 0.97142857]
Theta= [1 1]
Theta gorro= [0.97142857 0.97142857]
Theta= [1 1]
Theta gorro= [0.97142857 0.97142857]
Theta= [1 1]
Theta gorro= [0.97142857 0.97142857]
Theta= [1 1]
Theta gorro= [0.9

array([0.97142857, 0.97142857])

In [179]:
print ( accuracy_artesanal(Xt,yt, theta2) )
print ( accuracy_artesanal(Xv,yv,theta2) )

0.2571428571428571
0.21666666666666667


### Implementación en Scikit-Learn

In [9]:
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [10]:
clasif = Perceptron(max_iter=T,fit_intercept=False)

In [11]:
Sn = pd.DataFrame({'x1':x1,'x2':x2})
Sn['y'] = np.logical_or(Sn['x1'],Sn['x2']).astype(int)
Sn.head(2)

x1  x2  y
0   0   0  0
1   0   0  0

In [12]:
X = Sn[['x1','x2']]
y = Sn['y'] # Es una serie

Xt, Xv, yt, yv = train_test_split(X,y,train_size=0.7) # El 70 % de los datos ira a entrenamiento

clasif.fit(Xt,yt)

Perceptron(fit_intercept=False, max_iter=10000)

##### $\vec{\theta}$

In [14]:
clasif.coef_

array([[1., 1.]])

##### $\theta_0$

In [15]:
clasif.intercept_

array([0.])

##### Verificar que tan bueno es el modelo

In [16]:
print( accuracy_score(y_true=yt , y_pred=clasif.predict(Xt) ) ) # Porcentaje de aciertos con el de entrenamiento
print(accuracy_score( y_true=yv, y_pred=clasif.predict(Xv) ) )# Porcentaje de aciertos con el de validación

1.0
1.0


In [44]:
confusion_matrix(y_true=yv ,y_pred=clasif.predict(Xv) )# En Validación

array([[14,  0],
       [ 0, 46]])

In [18]:
confusion_matrix( y_true=yt , y_pred=clasif.predict(Xt) )

array([[ 33,   0],
       [  0, 107]])

0-->0 42  

0-->1 0  (Falso Positivo)

1-->0 18 (Falsos Negativos)

1-->1 0 